[package]
name = "pi_vec_remain"
version = "0.2.1"
authors = ["zmax <zmax@gaia.world>"]
edition = "2021"
description = "vec remain range"
repository = "https://github.com/GaiaWorld/pi_arr.git"
license = "MIT OR Apache-2.0"
keywords = ["pi", "vec", "remain"]
